// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package user_pool_client

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AccessTokenValidity, b.ko.Spec.AccessTokenValidity) {
		delta.Add("Spec.AccessTokenValidity", a.ko.Spec.AccessTokenValidity, b.ko.Spec.AccessTokenValidity)
	} else if a.ko.Spec.AccessTokenValidity != nil && b.ko.Spec.AccessTokenValidity != nil {
		if *a.ko.Spec.AccessTokenValidity != *b.ko.Spec.AccessTokenValidity {
			delta.Add("Spec.AccessTokenValidity", a.ko.Spec.AccessTokenValidity, b.ko.Spec.AccessTokenValidity)
		}
	}
	if len(a.ko.Spec.AllowedOAuthFlows) != len(b.ko.Spec.AllowedOAuthFlows) {
		delta.Add("Spec.AllowedOAuthFlows", a.ko.Spec.AllowedOAuthFlows, b.ko.Spec.AllowedOAuthFlows)
	} else if len(a.ko.Spec.AllowedOAuthFlows) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.AllowedOAuthFlows, b.ko.Spec.AllowedOAuthFlows) {
			delta.Add("Spec.AllowedOAuthFlows", a.ko.Spec.AllowedOAuthFlows, b.ko.Spec.AllowedOAuthFlows)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AllowedOAuthFlowsUserPoolClient, b.ko.Spec.AllowedOAuthFlowsUserPoolClient) {
		delta.Add("Spec.AllowedOAuthFlowsUserPoolClient", a.ko.Spec.AllowedOAuthFlowsUserPoolClient, b.ko.Spec.AllowedOAuthFlowsUserPoolClient)
	} else if a.ko.Spec.AllowedOAuthFlowsUserPoolClient != nil && b.ko.Spec.AllowedOAuthFlowsUserPoolClient != nil {
		if *a.ko.Spec.AllowedOAuthFlowsUserPoolClient != *b.ko.Spec.AllowedOAuthFlowsUserPoolClient {
			delta.Add("Spec.AllowedOAuthFlowsUserPoolClient", a.ko.Spec.AllowedOAuthFlowsUserPoolClient, b.ko.Spec.AllowedOAuthFlowsUserPoolClient)
		}
	}
	if len(a.ko.Spec.AllowedOAuthScopes) != len(b.ko.Spec.AllowedOAuthScopes) {
		delta.Add("Spec.AllowedOAuthScopes", a.ko.Spec.AllowedOAuthScopes, b.ko.Spec.AllowedOAuthScopes)
	} else if len(a.ko.Spec.AllowedOAuthScopes) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.AllowedOAuthScopes, b.ko.Spec.AllowedOAuthScopes) {
			delta.Add("Spec.AllowedOAuthScopes", a.ko.Spec.AllowedOAuthScopes, b.ko.Spec.AllowedOAuthScopes)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration, b.ko.Spec.AnalyticsConfiguration) {
		delta.Add("Spec.AnalyticsConfiguration", a.ko.Spec.AnalyticsConfiguration, b.ko.Spec.AnalyticsConfiguration)
	} else if a.ko.Spec.AnalyticsConfiguration != nil && b.ko.Spec.AnalyticsConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration.ApplicationARN, b.ko.Spec.AnalyticsConfiguration.ApplicationARN) {
			delta.Add("Spec.AnalyticsConfiguration.ApplicationARN", a.ko.Spec.AnalyticsConfiguration.ApplicationARN, b.ko.Spec.AnalyticsConfiguration.ApplicationARN)
		} else if a.ko.Spec.AnalyticsConfiguration.ApplicationARN != nil && b.ko.Spec.AnalyticsConfiguration.ApplicationARN != nil {
			if *a.ko.Spec.AnalyticsConfiguration.ApplicationARN != *b.ko.Spec.AnalyticsConfiguration.ApplicationARN {
				delta.Add("Spec.AnalyticsConfiguration.ApplicationARN", a.ko.Spec.AnalyticsConfiguration.ApplicationARN, b.ko.Spec.AnalyticsConfiguration.ApplicationARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration.ApplicationID, b.ko.Spec.AnalyticsConfiguration.ApplicationID) {
			delta.Add("Spec.AnalyticsConfiguration.ApplicationID", a.ko.Spec.AnalyticsConfiguration.ApplicationID, b.ko.Spec.AnalyticsConfiguration.ApplicationID)
		} else if a.ko.Spec.AnalyticsConfiguration.ApplicationID != nil && b.ko.Spec.AnalyticsConfiguration.ApplicationID != nil {
			if *a.ko.Spec.AnalyticsConfiguration.ApplicationID != *b.ko.Spec.AnalyticsConfiguration.ApplicationID {
				delta.Add("Spec.AnalyticsConfiguration.ApplicationID", a.ko.Spec.AnalyticsConfiguration.ApplicationID, b.ko.Spec.AnalyticsConfiguration.ApplicationID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration.ExternalID, b.ko.Spec.AnalyticsConfiguration.ExternalID) {
			delta.Add("Spec.AnalyticsConfiguration.ExternalID", a.ko.Spec.AnalyticsConfiguration.ExternalID, b.ko.Spec.AnalyticsConfiguration.ExternalID)
		} else if a.ko.Spec.AnalyticsConfiguration.ExternalID != nil && b.ko.Spec.AnalyticsConfiguration.ExternalID != nil {
			if *a.ko.Spec.AnalyticsConfiguration.ExternalID != *b.ko.Spec.AnalyticsConfiguration.ExternalID {
				delta.Add("Spec.AnalyticsConfiguration.ExternalID", a.ko.Spec.AnalyticsConfiguration.ExternalID, b.ko.Spec.AnalyticsConfiguration.ExternalID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration.RoleARN, b.ko.Spec.AnalyticsConfiguration.RoleARN) {
			delta.Add("Spec.AnalyticsConfiguration.RoleARN", a.ko.Spec.AnalyticsConfiguration.RoleARN, b.ko.Spec.AnalyticsConfiguration.RoleARN)
		} else if a.ko.Spec.AnalyticsConfiguration.RoleARN != nil && b.ko.Spec.AnalyticsConfiguration.RoleARN != nil {
			if *a.ko.Spec.AnalyticsConfiguration.RoleARN != *b.ko.Spec.AnalyticsConfiguration.RoleARN {
				delta.Add("Spec.AnalyticsConfiguration.RoleARN", a.ko.Spec.AnalyticsConfiguration.RoleARN, b.ko.Spec.AnalyticsConfiguration.RoleARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AnalyticsConfiguration.UserDataShared, b.ko.Spec.AnalyticsConfiguration.UserDataShared) {
			delta.Add("Spec.AnalyticsConfiguration.UserDataShared", a.ko.Spec.AnalyticsConfiguration.UserDataShared, b.ko.Spec.AnalyticsConfiguration.UserDataShared)
		} else if a.ko.Spec.AnalyticsConfiguration.UserDataShared != nil && b.ko.Spec.AnalyticsConfiguration.UserDataShared != nil {
			if *a.ko.Spec.AnalyticsConfiguration.UserDataShared != *b.ko.Spec.AnalyticsConfiguration.UserDataShared {
				delta.Add("Spec.AnalyticsConfiguration.UserDataShared", a.ko.Spec.AnalyticsConfiguration.UserDataShared, b.ko.Spec.AnalyticsConfiguration.UserDataShared)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AuthSessionValidity, b.ko.Spec.AuthSessionValidity) {
		delta.Add("Spec.AuthSessionValidity", a.ko.Spec.AuthSessionValidity, b.ko.Spec.AuthSessionValidity)
	} else if a.ko.Spec.AuthSessionValidity != nil && b.ko.Spec.AuthSessionValidity != nil {
		if *a.ko.Spec.AuthSessionValidity != *b.ko.Spec.AuthSessionValidity {
			delta.Add("Spec.AuthSessionValidity", a.ko.Spec.AuthSessionValidity, b.ko.Spec.AuthSessionValidity)
		}
	}
	if len(a.ko.Spec.CallbackURLs) != len(b.ko.Spec.CallbackURLs) {
		delta.Add("Spec.CallbackURLs", a.ko.Spec.CallbackURLs, b.ko.Spec.CallbackURLs)
	} else if len(a.ko.Spec.CallbackURLs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.CallbackURLs, b.ko.Spec.CallbackURLs) {
			delta.Add("Spec.CallbackURLs", a.ko.Spec.CallbackURLs, b.ko.Spec.CallbackURLs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DefaultRedirectURI, b.ko.Spec.DefaultRedirectURI) {
		delta.Add("Spec.DefaultRedirectURI", a.ko.Spec.DefaultRedirectURI, b.ko.Spec.DefaultRedirectURI)
	} else if a.ko.Spec.DefaultRedirectURI != nil && b.ko.Spec.DefaultRedirectURI != nil {
		if *a.ko.Spec.DefaultRedirectURI != *b.ko.Spec.DefaultRedirectURI {
			delta.Add("Spec.DefaultRedirectURI", a.ko.Spec.DefaultRedirectURI, b.ko.Spec.DefaultRedirectURI)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EnablePropagateAdditionalUserContextData, b.ko.Spec.EnablePropagateAdditionalUserContextData) {
		delta.Add("Spec.EnablePropagateAdditionalUserContextData", a.ko.Spec.EnablePropagateAdditionalUserContextData, b.ko.Spec.EnablePropagateAdditionalUserContextData)
	} else if a.ko.Spec.EnablePropagateAdditionalUserContextData != nil && b.ko.Spec.EnablePropagateAdditionalUserContextData != nil {
		if *a.ko.Spec.EnablePropagateAdditionalUserContextData != *b.ko.Spec.EnablePropagateAdditionalUserContextData {
			delta.Add("Spec.EnablePropagateAdditionalUserContextData", a.ko.Spec.EnablePropagateAdditionalUserContextData, b.ko.Spec.EnablePropagateAdditionalUserContextData)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EnableTokenRevocation, b.ko.Spec.EnableTokenRevocation) {
		delta.Add("Spec.EnableTokenRevocation", a.ko.Spec.EnableTokenRevocation, b.ko.Spec.EnableTokenRevocation)
	} else if a.ko.Spec.EnableTokenRevocation != nil && b.ko.Spec.EnableTokenRevocation != nil {
		if *a.ko.Spec.EnableTokenRevocation != *b.ko.Spec.EnableTokenRevocation {
			delta.Add("Spec.EnableTokenRevocation", a.ko.Spec.EnableTokenRevocation, b.ko.Spec.EnableTokenRevocation)
		}
	}
	if len(a.ko.Spec.ExplicitAuthFlows) != len(b.ko.Spec.ExplicitAuthFlows) {
		delta.Add("Spec.ExplicitAuthFlows", a.ko.Spec.ExplicitAuthFlows, b.ko.Spec.ExplicitAuthFlows)
	} else if len(a.ko.Spec.ExplicitAuthFlows) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.ExplicitAuthFlows, b.ko.Spec.ExplicitAuthFlows) {
			delta.Add("Spec.ExplicitAuthFlows", a.ko.Spec.ExplicitAuthFlows, b.ko.Spec.ExplicitAuthFlows)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.GenerateSecret, b.ko.Spec.GenerateSecret) {
		delta.Add("Spec.GenerateSecret", a.ko.Spec.GenerateSecret, b.ko.Spec.GenerateSecret)
	} else if a.ko.Spec.GenerateSecret != nil && b.ko.Spec.GenerateSecret != nil {
		if *a.ko.Spec.GenerateSecret != *b.ko.Spec.GenerateSecret {
			delta.Add("Spec.GenerateSecret", a.ko.Spec.GenerateSecret, b.ko.Spec.GenerateSecret)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IDTokenValidity, b.ko.Spec.IDTokenValidity) {
		delta.Add("Spec.IDTokenValidity", a.ko.Spec.IDTokenValidity, b.ko.Spec.IDTokenValidity)
	} else if a.ko.Spec.IDTokenValidity != nil && b.ko.Spec.IDTokenValidity != nil {
		if *a.ko.Spec.IDTokenValidity != *b.ko.Spec.IDTokenValidity {
			delta.Add("Spec.IDTokenValidity", a.ko.Spec.IDTokenValidity, b.ko.Spec.IDTokenValidity)
		}
	}
	if len(a.ko.Spec.LogoutURLs) != len(b.ko.Spec.LogoutURLs) {
		delta.Add("Spec.LogoutURLs", a.ko.Spec.LogoutURLs, b.ko.Spec.LogoutURLs)
	} else if len(a.ko.Spec.LogoutURLs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.LogoutURLs, b.ko.Spec.LogoutURLs) {
			delta.Add("Spec.LogoutURLs", a.ko.Spec.LogoutURLs, b.ko.Spec.LogoutURLs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PreventUserExistenceErrors, b.ko.Spec.PreventUserExistenceErrors) {
		delta.Add("Spec.PreventUserExistenceErrors", a.ko.Spec.PreventUserExistenceErrors, b.ko.Spec.PreventUserExistenceErrors)
	} else if a.ko.Spec.PreventUserExistenceErrors != nil && b.ko.Spec.PreventUserExistenceErrors != nil {
		if *a.ko.Spec.PreventUserExistenceErrors != *b.ko.Spec.PreventUserExistenceErrors {
			delta.Add("Spec.PreventUserExistenceErrors", a.ko.Spec.PreventUserExistenceErrors, b.ko.Spec.PreventUserExistenceErrors)
		}
	}
	if len(a.ko.Spec.ReadAttributes) != len(b.ko.Spec.ReadAttributes) {
		delta.Add("Spec.ReadAttributes", a.ko.Spec.ReadAttributes, b.ko.Spec.ReadAttributes)
	} else if len(a.ko.Spec.ReadAttributes) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.ReadAttributes, b.ko.Spec.ReadAttributes) {
			delta.Add("Spec.ReadAttributes", a.ko.Spec.ReadAttributes, b.ko.Spec.ReadAttributes)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RefreshTokenValidity, b.ko.Spec.RefreshTokenValidity) {
		delta.Add("Spec.RefreshTokenValidity", a.ko.Spec.RefreshTokenValidity, b.ko.Spec.RefreshTokenValidity)
	} else if a.ko.Spec.RefreshTokenValidity != nil && b.ko.Spec.RefreshTokenValidity != nil {
		if *a.ko.Spec.RefreshTokenValidity != *b.ko.Spec.RefreshTokenValidity {
			delta.Add("Spec.RefreshTokenValidity", a.ko.Spec.RefreshTokenValidity, b.ko.Spec.RefreshTokenValidity)
		}
	}
	if len(a.ko.Spec.SupportedIdentityProviders) != len(b.ko.Spec.SupportedIdentityProviders) {
		delta.Add("Spec.SupportedIdentityProviders", a.ko.Spec.SupportedIdentityProviders, b.ko.Spec.SupportedIdentityProviders)
	} else if len(a.ko.Spec.SupportedIdentityProviders) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SupportedIdentityProviders, b.ko.Spec.SupportedIdentityProviders) {
			delta.Add("Spec.SupportedIdentityProviders", a.ko.Spec.SupportedIdentityProviders, b.ko.Spec.SupportedIdentityProviders)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TokenValidityUnits, b.ko.Spec.TokenValidityUnits) {
		delta.Add("Spec.TokenValidityUnits", a.ko.Spec.TokenValidityUnits, b.ko.Spec.TokenValidityUnits)
	} else if a.ko.Spec.TokenValidityUnits != nil && b.ko.Spec.TokenValidityUnits != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.TokenValidityUnits.AccessToken, b.ko.Spec.TokenValidityUnits.AccessToken) {
			delta.Add("Spec.TokenValidityUnits.AccessToken", a.ko.Spec.TokenValidityUnits.AccessToken, b.ko.Spec.TokenValidityUnits.AccessToken)
		} else if a.ko.Spec.TokenValidityUnits.AccessToken != nil && b.ko.Spec.TokenValidityUnits.AccessToken != nil {
			if *a.ko.Spec.TokenValidityUnits.AccessToken != *b.ko.Spec.TokenValidityUnits.AccessToken {
				delta.Add("Spec.TokenValidityUnits.AccessToken", a.ko.Spec.TokenValidityUnits.AccessToken, b.ko.Spec.TokenValidityUnits.AccessToken)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.TokenValidityUnits.IDToken, b.ko.Spec.TokenValidityUnits.IDToken) {
			delta.Add("Spec.TokenValidityUnits.IDToken", a.ko.Spec.TokenValidityUnits.IDToken, b.ko.Spec.TokenValidityUnits.IDToken)
		} else if a.ko.Spec.TokenValidityUnits.IDToken != nil && b.ko.Spec.TokenValidityUnits.IDToken != nil {
			if *a.ko.Spec.TokenValidityUnits.IDToken != *b.ko.Spec.TokenValidityUnits.IDToken {
				delta.Add("Spec.TokenValidityUnits.IDToken", a.ko.Spec.TokenValidityUnits.IDToken, b.ko.Spec.TokenValidityUnits.IDToken)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.TokenValidityUnits.RefreshToken, b.ko.Spec.TokenValidityUnits.RefreshToken) {
			delta.Add("Spec.TokenValidityUnits.RefreshToken", a.ko.Spec.TokenValidityUnits.RefreshToken, b.ko.Spec.TokenValidityUnits.RefreshToken)
		} else if a.ko.Spec.TokenValidityUnits.RefreshToken != nil && b.ko.Spec.TokenValidityUnits.RefreshToken != nil {
			if *a.ko.Spec.TokenValidityUnits.RefreshToken != *b.ko.Spec.TokenValidityUnits.RefreshToken {
				delta.Add("Spec.TokenValidityUnits.RefreshToken", a.ko.Spec.TokenValidityUnits.RefreshToken, b.ko.Spec.TokenValidityUnits.RefreshToken)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID) {
		delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
	} else if a.ko.Spec.UserPoolID != nil && b.ko.Spec.UserPoolID != nil {
		if *a.ko.Spec.UserPoolID != *b.ko.Spec.UserPoolID {
			delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef) {
		delta.Add("Spec.UserPoolRef", a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef)
	}
	if len(a.ko.Spec.WriteAttributes) != len(b.ko.Spec.WriteAttributes) {
		delta.Add("Spec.WriteAttributes", a.ko.Spec.WriteAttributes, b.ko.Spec.WriteAttributes)
	} else if len(a.ko.Spec.WriteAttributes) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.WriteAttributes, b.ko.Spec.WriteAttributes) {
			delta.Add("Spec.WriteAttributes", a.ko.Spec.WriteAttributes, b.ko.Spec.WriteAttributes)
		}
	}

	return delta
}
