// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package user_pool_client

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cognitoidentityprovider-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.UserPoolClient{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeUserPoolClientOutput
	resp, err = rm.sdkapi.DescribeUserPoolClient(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeUserPoolClient", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.UserPoolClient.AccessTokenValidity != nil {
		accessTokenValidityCopy := int64(*resp.UserPoolClient.AccessTokenValidity)
		ko.Spec.AccessTokenValidity = &accessTokenValidityCopy
	} else {
		ko.Spec.AccessTokenValidity = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlows != nil {
		f1 := []*string{}
		for _, f1iter := range resp.UserPoolClient.AllowedOAuthFlows {
			var f1elem *string
			f1elem = aws.String(string(f1iter))
			f1 = append(f1, f1elem)
		}
		ko.Spec.AllowedOAuthFlows = f1
	} else {
		ko.Spec.AllowedOAuthFlows = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient != nil {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient
	} else {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = nil
	}
	if resp.UserPoolClient.AllowedOAuthScopes != nil {
		ko.Spec.AllowedOAuthScopes = aws.StringSlice(resp.UserPoolClient.AllowedOAuthScopes)
	} else {
		ko.Spec.AllowedOAuthScopes = nil
	}
	if resp.UserPoolClient.AnalyticsConfiguration != nil {
		f4 := &svcapitypes.AnalyticsConfigurationType{}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn != nil {
			f4.ApplicationARN = resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationId != nil {
			f4.ApplicationID = resp.UserPoolClient.AnalyticsConfiguration.ApplicationId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ExternalId != nil {
			f4.ExternalID = resp.UserPoolClient.AnalyticsConfiguration.ExternalId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.RoleArn != nil {
			f4.RoleARN = resp.UserPoolClient.AnalyticsConfiguration.RoleArn
		}
		f4.UserDataShared = &resp.UserPoolClient.AnalyticsConfiguration.UserDataShared
		ko.Spec.AnalyticsConfiguration = f4
	} else {
		ko.Spec.AnalyticsConfiguration = nil
	}
	if resp.UserPoolClient.AuthSessionValidity != nil {
		authSessionValidityCopy := int64(*resp.UserPoolClient.AuthSessionValidity)
		ko.Spec.AuthSessionValidity = &authSessionValidityCopy
	} else {
		ko.Spec.AuthSessionValidity = nil
	}
	if resp.UserPoolClient.CallbackURLs != nil {
		ko.Spec.CallbackURLs = aws.StringSlice(resp.UserPoolClient.CallbackURLs)
	} else {
		ko.Spec.CallbackURLs = nil
	}
	if resp.UserPoolClient.ClientId != nil {
		ko.Status.ID = resp.UserPoolClient.ClientId
	} else {
		ko.Status.ID = nil
	}
	if resp.UserPoolClient.ClientName != nil {
		ko.Spec.Name = resp.UserPoolClient.ClientName
	} else {
		ko.Spec.Name = nil
	}
	if resp.UserPoolClient.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.UserPoolClient.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.UserPoolClient.DefaultRedirectURI != nil {
		ko.Spec.DefaultRedirectURI = resp.UserPoolClient.DefaultRedirectURI
	} else {
		ko.Spec.DefaultRedirectURI = nil
	}
	if resp.UserPoolClient.EnablePropagateAdditionalUserContextData != nil {
		ko.Spec.EnablePropagateAdditionalUserContextData = resp.UserPoolClient.EnablePropagateAdditionalUserContextData
	} else {
		ko.Spec.EnablePropagateAdditionalUserContextData = nil
	}
	if resp.UserPoolClient.EnableTokenRevocation != nil {
		ko.Spec.EnableTokenRevocation = resp.UserPoolClient.EnableTokenRevocation
	} else {
		ko.Spec.EnableTokenRevocation = nil
	}
	if resp.UserPoolClient.ExplicitAuthFlows != nil {
		f13 := []*string{}
		for _, f13iter := range resp.UserPoolClient.ExplicitAuthFlows {
			var f13elem *string
			f13elem = aws.String(string(f13iter))
			f13 = append(f13, f13elem)
		}
		ko.Spec.ExplicitAuthFlows = f13
	} else {
		ko.Spec.ExplicitAuthFlows = nil
	}
	if resp.UserPoolClient.IdTokenValidity != nil {
		idTokenValidityCopy := int64(*resp.UserPoolClient.IdTokenValidity)
		ko.Spec.IDTokenValidity = &idTokenValidityCopy
	} else {
		ko.Spec.IDTokenValidity = nil
	}
	if resp.UserPoolClient.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = &metav1.Time{*resp.UserPoolClient.LastModifiedDate}
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.UserPoolClient.LogoutURLs != nil {
		ko.Spec.LogoutURLs = aws.StringSlice(resp.UserPoolClient.LogoutURLs)
	} else {
		ko.Spec.LogoutURLs = nil
	}
	if resp.UserPoolClient.PreventUserExistenceErrors != "" {
		ko.Spec.PreventUserExistenceErrors = aws.String(string(resp.UserPoolClient.PreventUserExistenceErrors))
	} else {
		ko.Spec.PreventUserExistenceErrors = nil
	}
	if resp.UserPoolClient.ReadAttributes != nil {
		ko.Spec.ReadAttributes = aws.StringSlice(resp.UserPoolClient.ReadAttributes)
	} else {
		ko.Spec.ReadAttributes = nil
	}
	refreshTokenValidityCopy := int64(resp.UserPoolClient.RefreshTokenValidity)
	ko.Spec.RefreshTokenValidity = &refreshTokenValidityCopy
	if resp.UserPoolClient.SupportedIdentityProviders != nil {
		ko.Spec.SupportedIdentityProviders = aws.StringSlice(resp.UserPoolClient.SupportedIdentityProviders)
	} else {
		ko.Spec.SupportedIdentityProviders = nil
	}
	if resp.UserPoolClient.TokenValidityUnits != nil {
		f21 := &svcapitypes.TokenValidityUnitsType{}
		if resp.UserPoolClient.TokenValidityUnits.AccessToken != "" {
			f21.AccessToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.AccessToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.IdToken != "" {
			f21.IDToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.IdToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.RefreshToken != "" {
			f21.RefreshToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.RefreshToken))
		}
		ko.Spec.TokenValidityUnits = f21
	} else {
		ko.Spec.TokenValidityUnits = nil
	}
	if resp.UserPoolClient.UserPoolId != nil {
		ko.Spec.UserPoolID = resp.UserPoolClient.UserPoolId
	} else {
		ko.Spec.UserPoolID = nil
	}
	if resp.UserPoolClient.WriteAttributes != nil {
		ko.Spec.WriteAttributes = aws.StringSlice(resp.UserPoolClient.WriteAttributes)
	} else {
		ko.Spec.WriteAttributes = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil || r.ko.Spec.UserPoolID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeUserPoolClientInput, error) {
	res := &svcsdk.DescribeUserPoolClientInput{}

	if r.ko.Status.ID != nil {
		res.ClientId = r.ko.Status.ID
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateUserPoolClientOutput
	_ = resp
	resp, err = rm.sdkapi.CreateUserPoolClient(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateUserPoolClient", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.UserPoolClient.AccessTokenValidity != nil {
		accessTokenValidityCopy := int64(*resp.UserPoolClient.AccessTokenValidity)
		ko.Spec.AccessTokenValidity = &accessTokenValidityCopy
	} else {
		ko.Spec.AccessTokenValidity = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlows != nil {
		f1 := []*string{}
		for _, f1iter := range resp.UserPoolClient.AllowedOAuthFlows {
			var f1elem *string
			f1elem = aws.String(string(f1iter))
			f1 = append(f1, f1elem)
		}
		ko.Spec.AllowedOAuthFlows = f1
	} else {
		ko.Spec.AllowedOAuthFlows = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient != nil {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient
	} else {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = nil
	}
	if resp.UserPoolClient.AllowedOAuthScopes != nil {
		ko.Spec.AllowedOAuthScopes = aws.StringSlice(resp.UserPoolClient.AllowedOAuthScopes)
	} else {
		ko.Spec.AllowedOAuthScopes = nil
	}
	if resp.UserPoolClient.AnalyticsConfiguration != nil {
		f4 := &svcapitypes.AnalyticsConfigurationType{}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn != nil {
			f4.ApplicationARN = resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationId != nil {
			f4.ApplicationID = resp.UserPoolClient.AnalyticsConfiguration.ApplicationId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ExternalId != nil {
			f4.ExternalID = resp.UserPoolClient.AnalyticsConfiguration.ExternalId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.RoleArn != nil {
			f4.RoleARN = resp.UserPoolClient.AnalyticsConfiguration.RoleArn
		}
		f4.UserDataShared = &resp.UserPoolClient.AnalyticsConfiguration.UserDataShared
		ko.Spec.AnalyticsConfiguration = f4
	} else {
		ko.Spec.AnalyticsConfiguration = nil
	}
	if resp.UserPoolClient.AuthSessionValidity != nil {
		authSessionValidityCopy := int64(*resp.UserPoolClient.AuthSessionValidity)
		ko.Spec.AuthSessionValidity = &authSessionValidityCopy
	} else {
		ko.Spec.AuthSessionValidity = nil
	}
	if resp.UserPoolClient.CallbackURLs != nil {
		ko.Spec.CallbackURLs = aws.StringSlice(resp.UserPoolClient.CallbackURLs)
	} else {
		ko.Spec.CallbackURLs = nil
	}
	if resp.UserPoolClient.ClientId != nil {
		ko.Status.ID = resp.UserPoolClient.ClientId
	} else {
		ko.Status.ID = nil
	}
	if resp.UserPoolClient.ClientName != nil {
		ko.Spec.Name = resp.UserPoolClient.ClientName
	} else {
		ko.Spec.Name = nil
	}
	if resp.UserPoolClient.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.UserPoolClient.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.UserPoolClient.DefaultRedirectURI != nil {
		ko.Spec.DefaultRedirectURI = resp.UserPoolClient.DefaultRedirectURI
	} else {
		ko.Spec.DefaultRedirectURI = nil
	}
	if resp.UserPoolClient.EnablePropagateAdditionalUserContextData != nil {
		ko.Spec.EnablePropagateAdditionalUserContextData = resp.UserPoolClient.EnablePropagateAdditionalUserContextData
	} else {
		ko.Spec.EnablePropagateAdditionalUserContextData = nil
	}
	if resp.UserPoolClient.EnableTokenRevocation != nil {
		ko.Spec.EnableTokenRevocation = resp.UserPoolClient.EnableTokenRevocation
	} else {
		ko.Spec.EnableTokenRevocation = nil
	}
	if resp.UserPoolClient.ExplicitAuthFlows != nil {
		f13 := []*string{}
		for _, f13iter := range resp.UserPoolClient.ExplicitAuthFlows {
			var f13elem *string
			f13elem = aws.String(string(f13iter))
			f13 = append(f13, f13elem)
		}
		ko.Spec.ExplicitAuthFlows = f13
	} else {
		ko.Spec.ExplicitAuthFlows = nil
	}
	if resp.UserPoolClient.IdTokenValidity != nil {
		idTokenValidityCopy := int64(*resp.UserPoolClient.IdTokenValidity)
		ko.Spec.IDTokenValidity = &idTokenValidityCopy
	} else {
		ko.Spec.IDTokenValidity = nil
	}
	if resp.UserPoolClient.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = &metav1.Time{*resp.UserPoolClient.LastModifiedDate}
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.UserPoolClient.LogoutURLs != nil {
		ko.Spec.LogoutURLs = aws.StringSlice(resp.UserPoolClient.LogoutURLs)
	} else {
		ko.Spec.LogoutURLs = nil
	}
	if resp.UserPoolClient.PreventUserExistenceErrors != "" {
		ko.Spec.PreventUserExistenceErrors = aws.String(string(resp.UserPoolClient.PreventUserExistenceErrors))
	} else {
		ko.Spec.PreventUserExistenceErrors = nil
	}
	if resp.UserPoolClient.ReadAttributes != nil {
		ko.Spec.ReadAttributes = aws.StringSlice(resp.UserPoolClient.ReadAttributes)
	} else {
		ko.Spec.ReadAttributes = nil
	}
	refreshTokenValidityCopy := int64(resp.UserPoolClient.RefreshTokenValidity)
	ko.Spec.RefreshTokenValidity = &refreshTokenValidityCopy
	if resp.UserPoolClient.SupportedIdentityProviders != nil {
		ko.Spec.SupportedIdentityProviders = aws.StringSlice(resp.UserPoolClient.SupportedIdentityProviders)
	} else {
		ko.Spec.SupportedIdentityProviders = nil
	}
	if resp.UserPoolClient.TokenValidityUnits != nil {
		f21 := &svcapitypes.TokenValidityUnitsType{}
		if resp.UserPoolClient.TokenValidityUnits.AccessToken != "" {
			f21.AccessToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.AccessToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.IdToken != "" {
			f21.IDToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.IdToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.RefreshToken != "" {
			f21.RefreshToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.RefreshToken))
		}
		ko.Spec.TokenValidityUnits = f21
	} else {
		ko.Spec.TokenValidityUnits = nil
	}
	if resp.UserPoolClient.UserPoolId != nil {
		ko.Spec.UserPoolID = resp.UserPoolClient.UserPoolId
	} else {
		ko.Spec.UserPoolID = nil
	}
	if resp.UserPoolClient.WriteAttributes != nil {
		ko.Spec.WriteAttributes = aws.StringSlice(resp.UserPoolClient.WriteAttributes)
	} else {
		ko.Spec.WriteAttributes = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateUserPoolClientInput, error) {
	res := &svcsdk.CreateUserPoolClientInput{}

	if r.ko.Spec.AccessTokenValidity != nil {
		accessTokenValidityCopy0 := *r.ko.Spec.AccessTokenValidity
		if accessTokenValidityCopy0 > math.MaxInt32 || accessTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AccessTokenValidity is of type int32")
		}
		accessTokenValidityCopy := int32(accessTokenValidityCopy0)
		res.AccessTokenValidity = &accessTokenValidityCopy
	}
	if r.ko.Spec.AllowedOAuthFlows != nil {
		f1 := []svcsdktypes.OAuthFlowType{}
		for _, f1iter := range r.ko.Spec.AllowedOAuthFlows {
			var f1elem string
			f1elem = string(*f1iter)
			f1 = append(f1, svcsdktypes.OAuthFlowType(f1elem))
		}
		res.AllowedOAuthFlows = f1
	}
	if r.ko.Spec.AllowedOAuthFlowsUserPoolClient != nil {
		res.AllowedOAuthFlowsUserPoolClient = *r.ko.Spec.AllowedOAuthFlowsUserPoolClient
	}
	if r.ko.Spec.AllowedOAuthScopes != nil {
		res.AllowedOAuthScopes = aws.ToStringSlice(r.ko.Spec.AllowedOAuthScopes)
	}
	if r.ko.Spec.AnalyticsConfiguration != nil {
		f4 := &svcsdktypes.AnalyticsConfigurationType{}
		if r.ko.Spec.AnalyticsConfiguration.ApplicationARN != nil {
			f4.ApplicationArn = r.ko.Spec.AnalyticsConfiguration.ApplicationARN
		}
		if r.ko.Spec.AnalyticsConfiguration.ApplicationID != nil {
			f4.ApplicationId = r.ko.Spec.AnalyticsConfiguration.ApplicationID
		}
		if r.ko.Spec.AnalyticsConfiguration.ExternalID != nil {
			f4.ExternalId = r.ko.Spec.AnalyticsConfiguration.ExternalID
		}
		if r.ko.Spec.AnalyticsConfiguration.RoleARN != nil {
			f4.RoleArn = r.ko.Spec.AnalyticsConfiguration.RoleARN
		}
		if r.ko.Spec.AnalyticsConfiguration.UserDataShared != nil {
			f4.UserDataShared = *r.ko.Spec.AnalyticsConfiguration.UserDataShared
		}
		res.AnalyticsConfiguration = f4
	}
	if r.ko.Spec.AuthSessionValidity != nil {
		authSessionValidityCopy0 := *r.ko.Spec.AuthSessionValidity
		if authSessionValidityCopy0 > math.MaxInt32 || authSessionValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AuthSessionValidity is of type int32")
		}
		authSessionValidityCopy := int32(authSessionValidityCopy0)
		res.AuthSessionValidity = &authSessionValidityCopy
	}
	if r.ko.Spec.CallbackURLs != nil {
		res.CallbackURLs = aws.ToStringSlice(r.ko.Spec.CallbackURLs)
	}
	if r.ko.Spec.Name != nil {
		res.ClientName = r.ko.Spec.Name
	}
	if r.ko.Spec.DefaultRedirectURI != nil {
		res.DefaultRedirectURI = r.ko.Spec.DefaultRedirectURI
	}
	if r.ko.Spec.EnablePropagateAdditionalUserContextData != nil {
		res.EnablePropagateAdditionalUserContextData = r.ko.Spec.EnablePropagateAdditionalUserContextData
	}
	if r.ko.Spec.EnableTokenRevocation != nil {
		res.EnableTokenRevocation = r.ko.Spec.EnableTokenRevocation
	}
	if r.ko.Spec.ExplicitAuthFlows != nil {
		f11 := []svcsdktypes.ExplicitAuthFlowsType{}
		for _, f11iter := range r.ko.Spec.ExplicitAuthFlows {
			var f11elem string
			f11elem = string(*f11iter)
			f11 = append(f11, svcsdktypes.ExplicitAuthFlowsType(f11elem))
		}
		res.ExplicitAuthFlows = f11
	}
	if r.ko.Spec.GenerateSecret != nil {
		res.GenerateSecret = *r.ko.Spec.GenerateSecret
	}
	if r.ko.Spec.IDTokenValidity != nil {
		idTokenValidityCopy0 := *r.ko.Spec.IDTokenValidity
		if idTokenValidityCopy0 > math.MaxInt32 || idTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field IdTokenValidity is of type int32")
		}
		idTokenValidityCopy := int32(idTokenValidityCopy0)
		res.IdTokenValidity = &idTokenValidityCopy
	}
	if r.ko.Spec.LogoutURLs != nil {
		res.LogoutURLs = aws.ToStringSlice(r.ko.Spec.LogoutURLs)
	}
	if r.ko.Spec.PreventUserExistenceErrors != nil {
		res.PreventUserExistenceErrors = svcsdktypes.PreventUserExistenceErrorTypes(*r.ko.Spec.PreventUserExistenceErrors)
	}
	if r.ko.Spec.ReadAttributes != nil {
		res.ReadAttributes = aws.ToStringSlice(r.ko.Spec.ReadAttributes)
	}
	if r.ko.Spec.RefreshTokenValidity != nil {
		refreshTokenValidityCopy0 := *r.ko.Spec.RefreshTokenValidity
		if refreshTokenValidityCopy0 > math.MaxInt32 || refreshTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field RefreshTokenValidity is of type int32")
		}
		refreshTokenValidityCopy := int32(refreshTokenValidityCopy0)
		res.RefreshTokenValidity = refreshTokenValidityCopy
	}
	if r.ko.Spec.SupportedIdentityProviders != nil {
		res.SupportedIdentityProviders = aws.ToStringSlice(r.ko.Spec.SupportedIdentityProviders)
	}
	if r.ko.Spec.TokenValidityUnits != nil {
		f19 := &svcsdktypes.TokenValidityUnitsType{}
		if r.ko.Spec.TokenValidityUnits.AccessToken != nil {
			f19.AccessToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.AccessToken)
		}
		if r.ko.Spec.TokenValidityUnits.IDToken != nil {
			f19.IdToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.IDToken)
		}
		if r.ko.Spec.TokenValidityUnits.RefreshToken != nil {
			f19.RefreshToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.RefreshToken)
		}
		res.TokenValidityUnits = f19
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}
	if r.ko.Spec.WriteAttributes != nil {
		res.WriteAttributes = aws.ToStringSlice(r.ko.Spec.WriteAttributes)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateUserPoolClientOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateUserPoolClient(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateUserPoolClient", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.UserPoolClient.AccessTokenValidity != nil {
		accessTokenValidityCopy := int64(*resp.UserPoolClient.AccessTokenValidity)
		ko.Spec.AccessTokenValidity = &accessTokenValidityCopy
	} else {
		ko.Spec.AccessTokenValidity = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlows != nil {
		f1 := []*string{}
		for _, f1iter := range resp.UserPoolClient.AllowedOAuthFlows {
			var f1elem *string
			f1elem = aws.String(string(f1iter))
			f1 = append(f1, f1elem)
		}
		ko.Spec.AllowedOAuthFlows = f1
	} else {
		ko.Spec.AllowedOAuthFlows = nil
	}
	if resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient != nil {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = resp.UserPoolClient.AllowedOAuthFlowsUserPoolClient
	} else {
		ko.Spec.AllowedOAuthFlowsUserPoolClient = nil
	}
	if resp.UserPoolClient.AllowedOAuthScopes != nil {
		ko.Spec.AllowedOAuthScopes = aws.StringSlice(resp.UserPoolClient.AllowedOAuthScopes)
	} else {
		ko.Spec.AllowedOAuthScopes = nil
	}
	if resp.UserPoolClient.AnalyticsConfiguration != nil {
		f4 := &svcapitypes.AnalyticsConfigurationType{}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn != nil {
			f4.ApplicationARN = resp.UserPoolClient.AnalyticsConfiguration.ApplicationArn
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ApplicationId != nil {
			f4.ApplicationID = resp.UserPoolClient.AnalyticsConfiguration.ApplicationId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.ExternalId != nil {
			f4.ExternalID = resp.UserPoolClient.AnalyticsConfiguration.ExternalId
		}
		if resp.UserPoolClient.AnalyticsConfiguration.RoleArn != nil {
			f4.RoleARN = resp.UserPoolClient.AnalyticsConfiguration.RoleArn
		}
		f4.UserDataShared = &resp.UserPoolClient.AnalyticsConfiguration.UserDataShared
		ko.Spec.AnalyticsConfiguration = f4
	} else {
		ko.Spec.AnalyticsConfiguration = nil
	}
	if resp.UserPoolClient.AuthSessionValidity != nil {
		authSessionValidityCopy := int64(*resp.UserPoolClient.AuthSessionValidity)
		ko.Spec.AuthSessionValidity = &authSessionValidityCopy
	} else {
		ko.Spec.AuthSessionValidity = nil
	}
	if resp.UserPoolClient.CallbackURLs != nil {
		ko.Spec.CallbackURLs = aws.StringSlice(resp.UserPoolClient.CallbackURLs)
	} else {
		ko.Spec.CallbackURLs = nil
	}
	if resp.UserPoolClient.ClientId != nil {
		ko.Status.ID = resp.UserPoolClient.ClientId
	} else {
		ko.Status.ID = nil
	}
	if resp.UserPoolClient.ClientName != nil {
		ko.Spec.Name = resp.UserPoolClient.ClientName
	} else {
		ko.Spec.Name = nil
	}
	if resp.UserPoolClient.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.UserPoolClient.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.UserPoolClient.DefaultRedirectURI != nil {
		ko.Spec.DefaultRedirectURI = resp.UserPoolClient.DefaultRedirectURI
	} else {
		ko.Spec.DefaultRedirectURI = nil
	}
	if resp.UserPoolClient.EnablePropagateAdditionalUserContextData != nil {
		ko.Spec.EnablePropagateAdditionalUserContextData = resp.UserPoolClient.EnablePropagateAdditionalUserContextData
	} else {
		ko.Spec.EnablePropagateAdditionalUserContextData = nil
	}
	if resp.UserPoolClient.EnableTokenRevocation != nil {
		ko.Spec.EnableTokenRevocation = resp.UserPoolClient.EnableTokenRevocation
	} else {
		ko.Spec.EnableTokenRevocation = nil
	}
	if resp.UserPoolClient.ExplicitAuthFlows != nil {
		f13 := []*string{}
		for _, f13iter := range resp.UserPoolClient.ExplicitAuthFlows {
			var f13elem *string
			f13elem = aws.String(string(f13iter))
			f13 = append(f13, f13elem)
		}
		ko.Spec.ExplicitAuthFlows = f13
	} else {
		ko.Spec.ExplicitAuthFlows = nil
	}
	if resp.UserPoolClient.IdTokenValidity != nil {
		idTokenValidityCopy := int64(*resp.UserPoolClient.IdTokenValidity)
		ko.Spec.IDTokenValidity = &idTokenValidityCopy
	} else {
		ko.Spec.IDTokenValidity = nil
	}
	if resp.UserPoolClient.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = &metav1.Time{*resp.UserPoolClient.LastModifiedDate}
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.UserPoolClient.LogoutURLs != nil {
		ko.Spec.LogoutURLs = aws.StringSlice(resp.UserPoolClient.LogoutURLs)
	} else {
		ko.Spec.LogoutURLs = nil
	}
	if resp.UserPoolClient.PreventUserExistenceErrors != "" {
		ko.Spec.PreventUserExistenceErrors = aws.String(string(resp.UserPoolClient.PreventUserExistenceErrors))
	} else {
		ko.Spec.PreventUserExistenceErrors = nil
	}
	if resp.UserPoolClient.ReadAttributes != nil {
		ko.Spec.ReadAttributes = aws.StringSlice(resp.UserPoolClient.ReadAttributes)
	} else {
		ko.Spec.ReadAttributes = nil
	}
	refreshTokenValidityCopy := int64(resp.UserPoolClient.RefreshTokenValidity)
	ko.Spec.RefreshTokenValidity = &refreshTokenValidityCopy
	if resp.UserPoolClient.SupportedIdentityProviders != nil {
		ko.Spec.SupportedIdentityProviders = aws.StringSlice(resp.UserPoolClient.SupportedIdentityProviders)
	} else {
		ko.Spec.SupportedIdentityProviders = nil
	}
	if resp.UserPoolClient.TokenValidityUnits != nil {
		f21 := &svcapitypes.TokenValidityUnitsType{}
		if resp.UserPoolClient.TokenValidityUnits.AccessToken != "" {
			f21.AccessToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.AccessToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.IdToken != "" {
			f21.IDToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.IdToken))
		}
		if resp.UserPoolClient.TokenValidityUnits.RefreshToken != "" {
			f21.RefreshToken = aws.String(string(resp.UserPoolClient.TokenValidityUnits.RefreshToken))
		}
		ko.Spec.TokenValidityUnits = f21
	} else {
		ko.Spec.TokenValidityUnits = nil
	}
	if resp.UserPoolClient.UserPoolId != nil {
		ko.Spec.UserPoolID = resp.UserPoolClient.UserPoolId
	} else {
		ko.Spec.UserPoolID = nil
	}
	if resp.UserPoolClient.WriteAttributes != nil {
		ko.Spec.WriteAttributes = aws.StringSlice(resp.UserPoolClient.WriteAttributes)
	} else {
		ko.Spec.WriteAttributes = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateUserPoolClientInput, error) {
	res := &svcsdk.UpdateUserPoolClientInput{}

	if r.ko.Spec.AccessTokenValidity != nil {
		accessTokenValidityCopy0 := *r.ko.Spec.AccessTokenValidity
		if accessTokenValidityCopy0 > math.MaxInt32 || accessTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AccessTokenValidity is of type int32")
		}
		accessTokenValidityCopy := int32(accessTokenValidityCopy0)
		res.AccessTokenValidity = &accessTokenValidityCopy
	}
	if r.ko.Spec.AllowedOAuthFlows != nil {
		f1 := []svcsdktypes.OAuthFlowType{}
		for _, f1iter := range r.ko.Spec.AllowedOAuthFlows {
			var f1elem string
			f1elem = string(*f1iter)
			f1 = append(f1, svcsdktypes.OAuthFlowType(f1elem))
		}
		res.AllowedOAuthFlows = f1
	}
	if r.ko.Spec.AllowedOAuthFlowsUserPoolClient != nil {
		res.AllowedOAuthFlowsUserPoolClient = *r.ko.Spec.AllowedOAuthFlowsUserPoolClient
	}
	if r.ko.Spec.AllowedOAuthScopes != nil {
		res.AllowedOAuthScopes = aws.ToStringSlice(r.ko.Spec.AllowedOAuthScopes)
	}
	if r.ko.Spec.AnalyticsConfiguration != nil {
		f4 := &svcsdktypes.AnalyticsConfigurationType{}
		if r.ko.Spec.AnalyticsConfiguration.ApplicationARN != nil {
			f4.ApplicationArn = r.ko.Spec.AnalyticsConfiguration.ApplicationARN
		}
		if r.ko.Spec.AnalyticsConfiguration.ApplicationID != nil {
			f4.ApplicationId = r.ko.Spec.AnalyticsConfiguration.ApplicationID
		}
		if r.ko.Spec.AnalyticsConfiguration.ExternalID != nil {
			f4.ExternalId = r.ko.Spec.AnalyticsConfiguration.ExternalID
		}
		if r.ko.Spec.AnalyticsConfiguration.RoleARN != nil {
			f4.RoleArn = r.ko.Spec.AnalyticsConfiguration.RoleARN
		}
		if r.ko.Spec.AnalyticsConfiguration.UserDataShared != nil {
			f4.UserDataShared = *r.ko.Spec.AnalyticsConfiguration.UserDataShared
		}
		res.AnalyticsConfiguration = f4
	}
	if r.ko.Spec.AuthSessionValidity != nil {
		authSessionValidityCopy0 := *r.ko.Spec.AuthSessionValidity
		if authSessionValidityCopy0 > math.MaxInt32 || authSessionValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AuthSessionValidity is of type int32")
		}
		authSessionValidityCopy := int32(authSessionValidityCopy0)
		res.AuthSessionValidity = &authSessionValidityCopy
	}
	if r.ko.Spec.CallbackURLs != nil {
		res.CallbackURLs = aws.ToStringSlice(r.ko.Spec.CallbackURLs)
	}
	if r.ko.Status.ID != nil {
		res.ClientId = r.ko.Status.ID
	}
	if r.ko.Spec.Name != nil {
		res.ClientName = r.ko.Spec.Name
	}
	if r.ko.Spec.DefaultRedirectURI != nil {
		res.DefaultRedirectURI = r.ko.Spec.DefaultRedirectURI
	}
	if r.ko.Spec.EnablePropagateAdditionalUserContextData != nil {
		res.EnablePropagateAdditionalUserContextData = r.ko.Spec.EnablePropagateAdditionalUserContextData
	}
	if r.ko.Spec.EnableTokenRevocation != nil {
		res.EnableTokenRevocation = r.ko.Spec.EnableTokenRevocation
	}
	if r.ko.Spec.ExplicitAuthFlows != nil {
		f12 := []svcsdktypes.ExplicitAuthFlowsType{}
		for _, f12iter := range r.ko.Spec.ExplicitAuthFlows {
			var f12elem string
			f12elem = string(*f12iter)
			f12 = append(f12, svcsdktypes.ExplicitAuthFlowsType(f12elem))
		}
		res.ExplicitAuthFlows = f12
	}
	if r.ko.Spec.IDTokenValidity != nil {
		idTokenValidityCopy0 := *r.ko.Spec.IDTokenValidity
		if idTokenValidityCopy0 > math.MaxInt32 || idTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field IdTokenValidity is of type int32")
		}
		idTokenValidityCopy := int32(idTokenValidityCopy0)
		res.IdTokenValidity = &idTokenValidityCopy
	}
	if r.ko.Spec.LogoutURLs != nil {
		res.LogoutURLs = aws.ToStringSlice(r.ko.Spec.LogoutURLs)
	}
	if r.ko.Spec.PreventUserExistenceErrors != nil {
		res.PreventUserExistenceErrors = svcsdktypes.PreventUserExistenceErrorTypes(*r.ko.Spec.PreventUserExistenceErrors)
	}
	if r.ko.Spec.ReadAttributes != nil {
		res.ReadAttributes = aws.ToStringSlice(r.ko.Spec.ReadAttributes)
	}
	if r.ko.Spec.RefreshTokenValidity != nil {
		refreshTokenValidityCopy0 := *r.ko.Spec.RefreshTokenValidity
		if refreshTokenValidityCopy0 > math.MaxInt32 || refreshTokenValidityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field RefreshTokenValidity is of type int32")
		}
		refreshTokenValidityCopy := int32(refreshTokenValidityCopy0)
		res.RefreshTokenValidity = refreshTokenValidityCopy
	}
	if r.ko.Spec.SupportedIdentityProviders != nil {
		res.SupportedIdentityProviders = aws.ToStringSlice(r.ko.Spec.SupportedIdentityProviders)
	}
	if r.ko.Spec.TokenValidityUnits != nil {
		f19 := &svcsdktypes.TokenValidityUnitsType{}
		if r.ko.Spec.TokenValidityUnits.AccessToken != nil {
			f19.AccessToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.AccessToken)
		}
		if r.ko.Spec.TokenValidityUnits.IDToken != nil {
			f19.IdToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.IDToken)
		}
		if r.ko.Spec.TokenValidityUnits.RefreshToken != nil {
			f19.RefreshToken = svcsdktypes.TimeUnitsType(*r.ko.Spec.TokenValidityUnits.RefreshToken)
		}
		res.TokenValidityUnits = f19
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}
	if r.ko.Spec.WriteAttributes != nil {
		res.WriteAttributes = aws.ToStringSlice(r.ko.Spec.WriteAttributes)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteUserPoolClientOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteUserPoolClient(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteUserPoolClient", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteUserPoolClientInput, error) {
	res := &svcsdk.DeleteUserPoolClientInput{}

	if r.ko.Status.ID != nil {
		res.ClientId = r.ko.Status.ID
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.UserPoolClient,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException":
		return true
	default:
		return false
	}
}
